### ISSUE TITLE
What is the reason/interpretation of adding 1 to no_of_unique_cat

### ISSUE THREAD

**Issue by jaircastruita** [mmortazavi/EntityEmbedding-Working_Example#1]
First of all, awesome work that you did here.

As it is pointed out on the paper of entity embeddings, I´m trying to train a DNN using entity embeddings to later use them to make visualizations (Using T-SNE and PCA).

My question is with respect the following line:

`vocab  = no_of_unique_cat + 1`

which I always end up with  the number of categories +1 making not possible to make a map 1 to 1 category  : embedding. What purpose does this +1 serves?

Thank you for your work btw!

**Comment by mmortazavi** [comment]
Glad to hear it was helpful. 
Great catch, that is absolutely unnecessary. I forgot to take it out. 

Here I was trying to implement a practical example from the paper of entity embeddings and many steps and suggestions from other blogposts (I think I missed referencing them too!), and in one blogpost this ` vocab = no_of_unique_cat + 1` was recommended and actually it was commented that is not unnecessary extra step but I forgot to take it out. 

Actually I have not noticed this, since I did not proceed with embedding visualizations. It will be nice to see you how you visualization the embedding using PCA, tSNE, or you may like to try UMAP too. 

I will fix this soon.

**Comment by mmortazavi** [comment]
fixed the confusion of the unnecessary variable `vocab = no_of_unique_cat + 1`.
